version: "3.8"
services:
    auth_service:
        build:
            context: ./auth_service
            dockerfile: Dockerfile
        container_name: auth_service
        depends_on:
            - db
        ports:
            - 3101:3101
        #restart: always
        #command: ["ls"]
        #volumes:
        #    - ./auth_service/:/app/
        #volumes:
        #    - ./auth_service/:/app/
        #    - /app/node_modules
        #environment:
        #DATABASE_URL: postgres://user:password@postgres:5432/db
        #NODE_ENV: development
        #PORT: 3101
        #DB_HOST: process.env.DB_HOST
        #POSTGRES_PASSWORD:
        #DB_NAME: user

    #postgres:
    #    image: postgres:15
    #    environment:
    #        # You can set the value of environment variables
    #        # in your docker-compose.yml file
    #        # Our Node app will use these to connect
    #        # to the database
    #        - POSTGRES_USER=root
    #        - POSTGRES_PASSWORD=root
    #        - POSTGRES_DB=user
    #    ports:
    #        # Standard port for PostgreSQL databases
    #        - "5432:5432"
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        command: postgres -c max_connections=200
        environment:
            POSTGRES_PASSWORD: exampleuserdb
