version: "3.8"
services:
    auth_service:
        build:
            #context: ./auth_service
            dockerfile: ./auth_service/Dockerfile
        container_name: auth_service
        depends_on:
            - postgres_db
        ports:
            - 3101:3101
        environment:
            JWT_SECRET: tinker
            PGHOST: postgres_db
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
        command: npm start

        volumes:
            - ./auth_service:/usr/src/app/
            - /usr/src/app/node_modules

    postgres_db:
        image: postgres:15
        restart: unless-stopped
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=user
        ports:
            - "5432:5432"
        volumes:
            #TODO Enable init script below
            # When the PostgreSQL container is started it will run any scripts
            # provided in the `docker-entrypoint-initdb.d` directory, this connects
            # our seed file to that directory so that it gets run
            - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql

    product_service:
        build:
            #context: ./auth_service
            dockerfile: ./product_service/Dockerfile
        container_name: product_service
        depends_on:
            - postgres_db
        ports:
            - 3000:3000
        environment:
            JWT_SECRET: tinker
            PGHOST: postgres_db
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
        command: npm start

        volumes:
            - ./product_service:/usr/src/app/
            - /usr/src/app/node_modules
