version: "3.8"
services:
    auth_service:
        build:
            context: ./auth_service
            dockerfile: Dockerfile
        container_name: auth_service
        ports:
            - 3101:3101
        #restart: always
        #command: ["ls"]
        #volumes:
        #    - ./auth_service/:/app/
        #volumes:
        #    - ./auth_service:/usr/src/app
        #    - /usr/src/app/node_modules
        environment:
            #DATABASE_URL: postgres://user:password@postgres:5432/db
            #NODE_ENV: development
            #PORT: 3101
            DB_HOST: localhost
            #POSTGRES_PASSWORD:
            DB_NAME: user
        #command: npm start

    #postgres:
    #    image: postgres:10.4
    #    ports:
    #        - "5432:5432"
    #    environment:
    #        DB_HOST: localhost
    #        POSTGRES_PASSWORD:
    #        DB_NAME: user
