name: Test Auth

on:
    push:
        branches:
            - main
        paths:
            - "auth_service/**"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/setup-node@v3
            - run: cd auth_service && npm ci && npm test
