name: Test-auth

on:
    push:
        branches: main
    pull_request:
        branches: main

jobs:
    # Label of the container job
    container-job:
        # Containers must run in Linux based operating systems
        runs-on: ubuntu-latest
        # Docker Hub image that `container-job` executes in
        container: node:10.18-jessie

        # Service containers to run with `container-job`
        services:
            # Label used to access the service container
            postgres:
                # Docker Hub image
                image: postgres
                # Provide the password for postgres
                env:
                    POSTGRES_PASSWORD: postgres
                # Set health checks to wait until postgres has started
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Run Auth Tests
              run: cd auth_service && npm install && npm test
              env:
                  JWT_SECRET: ${{secrets.JWT_SECRET}}
                  PGHOST: ${{secrets.PGHOST}}
                  DB_USERNAME: ${{secrets.DB_USERNAME}}
                  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
                  DB_NAME: ${{secrets.DB_NAME}}
                  #- run: npm install
                  #- run: npm run build --if-present
                  #- run: npm test

                  #  uses: actions/setup-node@v3
                  #  with:

                  #  cache: "npm"
