name: Test-auth

on:
    push:
        branches: main
    pull_request:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Run Auth Tests
              run: cd auth_service && npm install && npm test
              env:
                  JWT_SECRET: ${{secrets.JWT_SECRET}}
                  PGHOST: ${{secrets.PGHOST}}
                  DB_USERNAME: ${{secrets.DB_USERNAME}}
                  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
                  DB_NAME: ${{secrets.DB_NAME}}
            #- run: npm install
            #- run: npm run build --if-present
            #- run: npm test

            #  uses: actions/setup-node@v3
            #  with:

            #  cache: "npm"
