name: Test-auth

on:
    push:
        paths:
            - "auth_service/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: cd auth_service && npm ci && npm run test
